### ISSUE TITLE
not using all of eslint conf

### ISSUE THREAD

**Issue by bsr203** [kentcdodds/prettier-eslint-atom#1]
Hi Kent,
thanks for releasing the plugin.

Let me brief about the behavior.
Installed the plugin.
On format with `prettier-eslint-atom`, it does format with `prettier`, but not follows eslint rules. I still have eslint warning about `object-curly-spacing`, which allow me to fix (auto fix on nuclide save file).
I use `airbnb` eslint config. 
I previously also installed prettier plugin and I could see there is some difference in formatting between `prettier` and `prettier-eslint-atom`, so it may be using eslint config. But not sure why not `object-curly-spacing`, and others which can be auto fixed by eslint/nuclide plugin.

bsr.

**Comment by kentcdodds** [comment]
Hmmm... Could you do some investigation into why this is happening and maybe [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by bsr203** [comment]
sorry not providing much info, thought it might easy to see in your test env. will try. until, [this](https://github.com/jlongster/prettier/pull/123) is solved, won't be using this plugin. so may take a while to get around looking at this.

**Comment by kentcdodds** [comment]
This should be resolved now. Please let me know if you still have trouble :)
