### ISSUE TITLE
Respect .eslintignore?

### ISSUE THREAD

**Issue by robwise** [kentcdodds/prettier-eslint-atom#13]
Should we add the ability to prevent `formatOnSave` if the file being saved is in the `.eslintignore`?

**Comment by kentcdodds** [comment]
I think by default we should respect `.eslintignore` and not `formatOnSave`, but I'd accept an option that allowed you to say whether you want to format on save even with ignored files.

**Comment by robwise** [comment]
roger that, I will try and push something sometime this week
