### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/prettier-eslint-atom#14]
This could be my own setup problem, but I'm no longer seeing the plugin loaded when installing the latest version. It looks like things work fine with `v1.1.0`. [Here's the diff](https://github.com/kentcdodds/prettier-eslint-atom/compare/v1.1.0...v1.2.0). I'm thinking it may have something to do with [my move to `dist`](https://github.com/kentcdodds/prettier-eslint-atom/commit/b32fe1bd4653dc0f2651eefad6d21e4f29aaf071). But I update the `package.json` som I'm confused. Anyone have any ideas?

**Comment by kentcdodds** [comment]
So yeah, I'm not sure what's going on... Here's the source tab in devtools in atom:

<img width="232" alt="screen shot 2017-01-24 at 1 50 07 pm" src="https://cloud.githubusercontent.com/assets/1500684/22268371/2c5867b2-e23c-11e6-9a0c-d896fb240b99.png">

And here's the files in the `~/.atom/packages` directory:

<img width="482" alt="screen shot 2017-01-24 at 1 50 35 pm" src="https://cloud.githubusercontent.com/assets/1500684/22268385/39be0fce-e23c-11e6-9d21-9046a5c8ab48.png">

There are no errors in my console on startup. What's going on?

**Comment by damieng** [comment]
What do you see if you type `apm list` ?

**Comment by janis-kra** [comment]
Got the same behavior with `v1.2.1`, so your setup is not at fault @kentcdodds

**Comment by iGitScor** [comment]
I've just updated the plugin (`prettier-eslint-atom@2.0.1`) and I had not encountered any issue of loading

**Comment by kentcdodds** [comment]
Thanks friends!

@iGitScor, thanks, please note that this plugin has been renamed and you're using the old one.

Thanks for that confirmation @janis-kra 

@damieng, here's what I get when I do `apm list`:

```
[36mBuilt-in Atom Packages[39m (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.4.0
├── base16-tomorrow-light-theme@1.4.0
├── one-dark-ui@1.8.2
├── one-light-ui@1.8.2
├── one-dark-syntax@1.6.0
├── one-light-syntax@1.6.0
├── solarized-dark-syntax@1.1.1
├── solarized-light-syntax@1.1.1
├── about@1.7.2
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.14.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.33.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.23.2
├── background-tips@0.26.1
├── bookmarks@0.43.2
├── bracket-matcher@0.85.1
├── command-palette@0.39.1
├── deprecation-cop@0.55.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.204.5
├── fuzzy-finder@1.4.0
├── git-diff@1.2.0
├── go-to-line@0.31.2
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.1
├── link@0.31.2
├── markdown-preview@0.159.1
├── metrics@1.1.2
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.2
├── settings-view@0.244.0
├── snippets@1.0.4
├── spell-check@0.68.5
├── status-bar@1.6.0
├── styleguide@0.48.0
├── symbols-view@0.113.1
├── tabs@0.103.1
├── timecop@0.33.2
├── tree-view@0.211.1
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.39.0
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.1
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

[36mCommunity Packages (24)[39m /Users/kdodds/.atom/packages
├── atom-ternjs@0.17.0
├── autocomplete-emojis@2.5.0
├── autocomplete-json@5.2.0
├── autocomplete-modules@1.6.7
├── custom-invisibles@0.1.2
├── docblockr@0.9.1
├── editorconfig@2.2.0
├── expand-region@0.2.6
├── file-icons@2.0.12
├── highlight-selected@0.12.0
├── hyperclick@0.0.40
├── js-hyperclick@1.10.1
├── language-babel@2.50.0
├── language-dustjs@0.2.0
├── language-json5@1.1.0
├── linter@1.11.21
├── linter-eslint@8.0.0
├── linter-flow@5.5.0
├── linter-jsonlint@1.3.0
├── local-history@4.0.1
├── open-this@0.3.0
├── prettier-eslint@1.2.1
├── relative-numbers@0.7.1
└── vim-mode-plus@0.80.0
```

Looks like `prettier-eslint` is in there :-/

**Comment by damieng** [comment]
Seems to work fine for me.  Steps;

1. `cd %userprofile%\github`
2. `git clone git@github.com:kentcdodds/prettier-eslint-atom.git`
3. `apm link prettier-eslint-atom`
4. `cd prettier-eslint-atom`
5. `apm i`
6. `babel --copy-files --out-dir dist src`
7. launch atom

Then I went into a file, hit ctrl-alt-f and it reformatted my code.

**Comment by janis-kra** [comment]
@kentcdodds haven't figured out why yet, but the reason for the plugin not loading seems to be that the build is somehow borken? In `v1.1.0` the `lib` folder is correctly created, but for `v1.2.1` the `dist` folder does not exist (see my terminal output below)

```
jk  ~/.atom/packages 
→ apm install prettier-eslint@1.1.0
Installing prettier-eslint@1.1.0 to /Users/jk/.atom/packages ✓
 jk  ~/.atom/packages 
→ ls prettier-eslint/lib/
helpers.js              prettier-eslint-atom.js
 jk  ~/.atom/packages 
→ apm remove prettier-eslint/
Uninstalling prettier-eslint/ ✓
 jk  ~/.atom/packages 
→ apm install prettier-eslint
Installing prettier-eslint to /Users/jk/.atom/packages ✓
 jk  ~/.atom/packages 
→ ls prettier-eslint/
CHANGELOG.md       README.md          node_modules       package.json
CONTRIBUTING.md    keymaps            other              src
LICENSE            menus              package-scripts.js yarn.lock
```

**Comment by kentcdodds** [comment]
Oh! I'll bet it's because I `.gitignore` the `dist` directory because I don't like committing generated files... And `apm` doesn't appear to respect the `files` property in `package.json`. That's my guess anyway. Anyone know of how to configure `apm` which files to use for the publish?

**Comment by kentcdodds** [comment]
I just published the version with `dist` and it works now. But I'd really like to not have to commit those files to the repo, also I'd love to not have `yarn.lock` and other files in the package registry. Is there any way to do this?

**Comment by janis-kra** [comment]
Seems that you are not the only one with this issue, see https://github.com/atom/apm/issues/498

Although I did not understand it completely, there seems to be kind of a workaround for this (https://github.com/sindresorhus/atom-editorconfig/pull/153)? Also, this was merged into the apm repository a few months ago so maybe there's still hope

**Comment by kentcdodds** [comment]
I'm just going to close this issue. I think we've got things as resolved as I care to resolve them. Thanks!
