### ISSUE TITLE
Upgrade to latest prettier-eslint

### ISSUE THREAD

**Issue by aaronshaf** [kentcdodds/prettier-eslint-atom#18]
... to get prettier 0.17.0

**Comment by kentcdodds** [comment]
Actually, you should be able to just run `apm uninstall prettier-eslint-atom && apm install prettier-eslint-atom` and because the version ranges are the way they are it should update to the latest version of `prettier-eslint` (which has the latest `prettier`).

**Comment by kentcdodds** [comment]
This package has been deprecated. Please see the README for instructions on moving to the new plugin.
