### ISSUE TITLE
Refactoring and Repo Talk

### ISSUE THREAD

**Issue by robwise** [kentcdodds/prettier-eslint-atom#28]
I just had to refactor the whole codebase over at prettier-atom. I was getting user requirements and PRs that ended up putting conditionals everywhere. Would you be interested in me porting some of that over here (the refactoring I mean, not lots of conditionals lol)? 

Also, I'm thinking about making that repo extremely similar to this repo. But, I don't know, maybe it would make sense to go all of the way and just merge the two? And allow the eslint integration to be optional somehow via the user's Atom settings? That would help maintainability a lot and that way we could share updates. For example, prettier-atom now can run on embedded scopes on save (like if you have a script tag in your html file), which we'd otherwise have to sort of copy-and-paste over here.

Also, I really want to implement Jest testing snapshots because manual testing of the rapidly increasing configuration options and stories is becoming a nightmare.

**Comment by kentcdodds** [comment]
I'd be totally fine with it if the `prettier-atom` folks are fine with it (which appears to be mostly you these days anyway :smile:)

Also Jest snapshots are super 🔥

**Comment by robwise** [comment]
@jlongster what do you think?

**Comment by jlongster** [comment]
Sure, I will leave the editor integration up to you all :) I don't think this is a bad thing to do, but it should be default off and not encouraged. It makes things very slow and I recommend just running prettier interactively and then running eslint later.

But I agree that it feels bad to have multiple integrations that all have similar code.

It also makes it easier to evolve it, as we are thinking through some capabilities of prettier (like a server mode) we'll likely reach out to you all about implementing them on the editor side.

**Comment by kentcdodds** [comment]
I've deprecated this plugin. Thanks for all your work @robwise!
