### ISSUE TITLE
Typo on the readme

### ISSUE THREAD

**Issue by cloud-walker** [kentcdodds/prettier-eslint-atom#3]
<img width="556" alt="screen shot 2017-01-13 at 16 20 41" src="https://cloud.githubusercontent.com/assets/1144075/21935095/5a802654-d9ac-11e6-9fb9-b39eab1ea40e.png">

Don't think `apm install editorconfig` is the right package 😅 

I'll open a PR if you like 😄

**Comment by kentcdodds** [comment]
lol! Thanks for the catch! Yes, please do! And feel free to [add yourself to the contributors list](https://github.com/kentcdodds/prettier-eslint-atom/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)! This is a valuable contribution indeed!
