### ISSUE TITLE
The "on save" feature is not working

### ISSUE THREAD

**Issue by cloud-walker** [kentcdodds/prettier-eslint-atom#5]
I've emulated the exact readme gif situation, and when I do `cmd-shift-p` -> format it works well.

Nothing happens if I save or even if I use the keybinding provided (`shift-alt-f` right?).

I'm missing something? Maybe I need eslint on global scope? Or I have to disable the classic atom linter?

**Comment by kentcdodds** [comment]
Honestly, I'm not sure. I copied this from the [`prettier-atom` plugin](https://github.com/jlongster/prettier-atom) so I don't know whether it works 😅 Would you be able to dig a little more?

**Comment by cloud-walker** [comment]
I was supposing that 👍 , I don't have the time now, but I will be glad to help!

**Comment by cloud-walker** [comment]
Ok, i've installed `prettier` globally and now its working!

Maybe we need to doc that.

P.S.  the `prettier-atom` package seems too suffer by the same issue too!

**Comment by kentcdodds** [comment]
Interesting! This shouldn't be a requirement. We should actually look for the locally (to the open project) installed instance of `prettier` _and_ `eslint`. If they don't exist, we should try for a global version, if those don't exist, then we can use our own version (distributed with the package). What do you think?

**Comment by cloud-walker** [comment]
Agreed!

**Comment by kentcdodds** [comment]
Going to try to solve this directly in `prettier-eslint`: https://github.com/kentcdodds/prettier-eslint/issues/3

**Comment by kentcdodds** [comment]
This should be resolved now. Please let me know whether this is still an issue for you!
