### ISSUE TITLE
Format On Save setting not working

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/prettier-eslint-atom#8]
If I uncheck "Format On Save" it doesn't take into effect. I think there may be something wrong with [how we're reading that property](https://github.com/kentcdodds/prettier-eslint-atom/blob/master/lib/prettier-eslint-atom.js#L79-L81) or something... 🤔

**Comment by robwise** [comment]
👍 @kentcdodds I basically was using prettier + eslint in this way already except manually, so I will definitely have to check this project out. 

Let me know if you want help tackling anything. 

I was hoping to [go to the source](https://github.com/jlongster/prettier/issues/165#issuecomment-273645333) and convince everyone to at least support configuring enough Prettier options to allow someone to completely comply with airbnb/javascript after running the autofix (currently, there's an issue with wrapping ternaries being returned by a fat arrow, plus probably others I don't know about).

**Comment by kentcdodds** [comment]
Super! There are some things I'm hoping for (like include/exclude) if you could look into that, I'd appreciate it! Thanks again!
