### ISSUE TITLE
Add configuration option of file globs to ignore

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/prettier-eslint-atom#9]
This way you could disable the plugin entirely for certain projects (like at work where people aren't sold on prettier yet).

May also be nice to have the opposite option.

These options could be called:

- Exclude (list of globs)
- Include (list of globs)

Any prior art?

**Comment by robwise** [comment]
@kentcdodds How do you envision this interacting with the [scopes setting](https://github.com/kentcdodds/prettier-eslint-atom/blob/master/package.json#L79-L89)?

For example, if I make a whitelist glob of `*.jsx` but I remove `source.jsx` from my formatOnSave scopes, does it format or no?

This same sort of question comes up again when you consider the `.eslintignore` which also has globs. Which one "wins?"

**Comment by kentcdodds** [comment]
Great question! We should definitely document it well because it could be confusing. Actually, I think that if I use the hotkey or menu, it should work regardless of scope, includes/excludes or .eslintignore. We should only consider these options/config for the format on save functionality I think....

As for which wins, I say we be as conservative as possible. If the file is excluded via any option, then it should not format on save. And I think Include should be a whitelist. So if it's specified, then files should only format on save if they pass the other criteria (included in scope and not ignore) and match the include glob(s).

I'm open for other ideas. But this seems reasonable for me. I'm mostly concerned about my other projects where team members don't want me reformatting files with this. I want to exclude those projects.

**Comment by robwise** [comment]
Okay, I implemented exclude globs in https://github.com/kentcdodds/prettier-eslint-atom/pull/11 but didn't hit the includes so I didn't mark this resolved in that commit.

**Demo: I start out with bad formatting and `*helpers.js` in my globs, and when I save, nothing happens. When I empty out my globs, I save again, and prettier-eslint runs.**
![demo](https://cl.ly/0x3I2O3A4629/Screen%20Recording%202017-01-22%20at%2006.09%20PM.gif)

**Comment by kentcdodds** [comment]
This will be released in a few hours. Thanks again! Now I can enable the plugin full-time!
